# Generated by Django 5.1.2 on 2024-12-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
            ],
        ),
    ]
