# Generated by Django 5.1.2 on 2024-12-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0004_alter_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
    ]
